services:
  postgres:
    image: postgres:16
    container_name: postgres
    command: |
      postgres 
      -c log_statement=all 
      -c log_destination=stderr 
      -c hba_file=/etc/pg_hba.conf
      -c config_file=/etc/postgresql.conf
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sample
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    volumes:
      - ./conf/postgres/pg_hba.conf:/etc/pg_hba.conf
      - ./conf/postgres/postgresql.conf:/etc/postgresql.conf
      - ./init/:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      default:
        aliases:
          - postgres

volumes:
  postgres_data:

networks:
  default:
    name: pgbouncer_net
